// <auto-generated />
namespace AssetsManagementEF.Module.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_database07 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_database07));
        
        string IMigrationMetadata.Id
        {
            get { return "201712190937007_update_database07"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
