// <auto-generated />
namespace AssetsManagementEF.Module.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_deviation_cancelcloseuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_deviation_cancelcloseuser));
        
        string IMigrationMetadata.Id
        {
            get { return "202209260738379_add_deviation_cancelcloseuser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
