// <auto-generated />
namespace AssetsManagementEF.Module.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Contractor_DocFullCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Contractor_DocFullCode));
        
        string IMigrationMetadata.Id
        {
            get { return "202311090739361_add_Contractor_DocFullCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
