// <auto-generated />
namespace AssetsManagementEF.Module.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_back_KeyReviewer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_back_KeyReviewer));
        
        string IMigrationMetadata.Id
        {
            get { return "202511050748045_add_back_KeyReviewer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
