// <auto-generated />
namespace AssetsManagementEF.Module.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_workorder_LAFD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_workorder_LAFD));
        
        string IMigrationMetadata.Id
        {
            get { return "202511240407268_add_workorder_LAFD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
